In [52]:
import pandas as pd
import os 
from datetime import datetime

In [53]:
DATA_RAW_PATH = "../data/raw/traffic_data.csv"
DATA_PROCESSED_PATH = "../data/processed/traffic_data.csv"

COLUMNS = [
    "timestamp",
    "avenida",
    "velocidad",
    "densidad",
    "detenciones"
]

In [54]:
def create_dataset():
    os.makedirs(os.path.dirname(DATA_RAW_PATH), exist_ok=True)

    if not os.path.exists(DATA_RAW_PATH):
        df = pd.DataFrame(columns=COLUMNS)
        df.to_csv(DATA_RAW_PATH, index=False)
        print("Dataset creado")
    else:
        print("Dataset ya existe")

create_dataset()

Dataset ya existe

In [55]:
def add_record(avenida,velocidad, denssidad, detenciones):
    timestamp = datetime.now()

    new_data = pd.DataFrame({
        "timestamp": [timestamp],
        "avenida": [avenida],
        "velocidad": [velocidad],
        "densidad": [denssidad],
        "detenciones": [detenciones]
    })

    os.makedirs(os.path.dirname(DATA_RAW_PATH), exist_ok=True)

    if os.path.exists(DATA_RAW_PATH):
        df =  pd.read_csv(DATA_RAW_PATH)
        df = pd.concat([df, new_data], ignore_index=True)
    else:
        df = new_data
    df.to_csv(DATA_RAW_PATH, index=False)
    print("Registro agregado")

In [56]:
add_record("Lopez Mateos", 25, 3, 2)
add_record("Lopez Mateos", 20, 3, 2)
add_record("Lopez Mateos", 15, 3, 2)

Registro agregado
Registro agregado
Registro agregado

In [57]:
df = pd.read_csv(DATA_RAW_PATH)
print(df.head())

                    timestamp       avenida  velocidad  densidad  detenciones
0  2026-03-17 22:31:30.850956  Lopez Mateos         25         3            2
1  2026-03-17 22:31:30.859960  Lopez Mateos         20         3            2
2  2026-03-17 22:31:30.882579  Lopez Mateos         15         3            2
3  2026-03-17 22:42:42.487827  Lopez Mateos         25         3            2
4  2026-03-17 22:42:42.493310  Lopez Mateos         20         3            2

In [58]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
df = df.sort_values(by ="timestamp")

df.head()

                   timestamp       avenida  velocidad  densidad  detenciones
0 2026-03-17 22:31:30.850956  Lopez Mateos         25         3            2
1 2026-03-17 22:31:30.859960  Lopez Mateos         20         3            2
2 2026-03-17 22:31:30.882579  Lopez Mateos         15         3            2
3 2026-03-17 22:42:42.487827  Lopez Mateos         25         3            2
4 2026-03-17 22:42:42.493310  Lopez Mateos         20         3            2

In [59]:
def min_max_norm(series):
    min_val = series.min()
    max_val = series.max()
    if max_val == min_val:
        return pd.Series(0.0, index=series.index)
    return (series - min_val) / (max_val - min_val)

df["velocidad_norm"] = min_max_norm(df["velocidad"])
df["densidad_norm"] = min_max_norm(df["densidad"])
df["detenciones_norm"] = min_max_norm(df["detenciones"])

df.head()

,timestamp,avenida,velocidad,densidad,detenciones,velocidad_norm,densidad_norm,detenciones_norm
0,2026-03-17 22:31:30.850956,Lopez Mateos,25,3,2,1.0,0.0,0.0
1,2026-03-17 22:31:30.859960,Lopez Mateos,20,3,2,0.5,0.0,0.0
2,2026-03-17 22:31:30.882579,Lopez Mateos,15,3,2,0.0,0.0,0.0
3,2026-03-17 22:42:42.487827,Lopez Mateos,25,3,2,1.0,0.0,0.0
4,2026-03-17 22:42:42.493310,Lopez Mateos,20,3,2,0.5,0.0,0.0

In [60]:
os.makedirs(os.path.dirname(DATA_PROCESSED_PATH), exist_ok=True)
df.to_csv(DATA_PROCESSED_PATH, index=False)
print("Datos procesados guardados")

Datos procesados guardados

In [61]:
df["TSI"] = (df["densidad_norm"] + df["detenciones_norm"]) / (df["velocidad_norm"] + 0.01)
df[["timestamp", "avenida", "TSI"]].head()

                   timestamp       avenida  TSI
0 2026-03-17 22:31:30.850956  Lopez Mateos  0.0
1 2026-03-17 22:31:30.859960  Lopez Mateos  0.0
2 2026-03-17 22:31:30.882579  Lopez Mateos  0.0
3 2026-03-17 22:42:42.487827  Lopez Mateos  0.0
4 2026-03-17 22:42:42.493310  Lopez Mateos  0.0